name: Java CI with Maven

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with JaCoCo
        run: mvn clean test jacoco:report

      - name: Show coverage summary
        run: |
          echo "=== JaCoCo Coverage Summary ==="
          cat target/site/jacoco/jacoco.csv || true

      - name: Check JaCoCo coverage
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: |
            target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          fail-build: true

      - name: Upload JaCoCo report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
